---
title: "On Computers and Computing"
---

## Introduction to Computer Science


## Topics that will be covered:

- What do these ‘Computer Science’ words mean?
- What exactly does it mean to compute?
- What’s the history of Computing?

## Science

- A particular area of science
- A systematically organized body of knowledge on particular subject
- knowledge of any kind
- The intellectual and practical activity encompassing the systematic study of the structure and behavior of the physical and natural world through observation and experiment

## Computer

- The term "computer", in use from the early 17th century (the first known written reference dates from 1613) meant "one who computes": a person performing mathematical calculations, before electronic computers became commercially available.
- Alan Turing described the "human computer" as someone who is
"supposed to be following fixed rules; he has no authority to deviate from
them in any detail." Teams of people, from the late nineteenth century
onwards, were used to undertake long and often tedious calculations; the
work was divided so that this could be done in parallel. The same
calculations were frequently performed independently by separate teams
to check the correctness of the results.
- Since the end of the 20th century, the term "human computer" has also
been applied to individuals with prodigious powers of mental arithmetic,
also known as mental calculators.

# NASA High Speed Flight Station "Computer Room”

Early "computers" at work, summer 1949. In the terminology of that period, computers were employees who performed the arduous task of transcribing raw data from rolls of celluloid film and strips of oscillograph paper and then, using slide rules and electric calculators, reducing into standard engineering units.

# The History of Computing

- **14th C - Abacus** - an instrument for performing calculations by
sliding counters along rods or in grooves.
- **17th C - Slide rule** - a manual device used for calculation that consists in its simple form of a ruler and a movable middle piece which are graduated with similar logarithmic scales.
- **1642 - Pascaline -** a mechanical calculator built by Blaise Pascal, a 17th century mathematician, for whom the Pascal computer programming language was named.
- **1804 Jacquard loom -** a loom programmed with punched cards
invented by Joseph Marie Jacquard.
- **1850-Difference Engine, Analytical Engine-**Charles Babbage and Ada Byron. Babbage's description, in 1837, of the Analytical Engine, a hand cranked, mechanical digital computer anticipated virtually every aspect of present-day computers. It wasn't until over a 100years later that another all purpose computer was conceived. Sketch of the Engine and notes by Ada Byron King, Countess of Lovelace.
- **1939-1942- Atanasoff Berry Computer**-built at Iowa State by Prof. JohnV. Atanas off and graduate student Clifford Berry.Represented several"firsts" in computing, including a binary system of arithmetic, parallel processing, regenerative memory, separation of memory and computing functions, and more. Weighed 750 lbs. and had a memory storage of3,000 bits (0.4K).Recorded numbers by scorching marks into cards as it worked through a problem.
- **1940s - Colossus -** a vacuum tube computing machine which broke Hitler's codes during
WW II. It was instrumental in helping Turing break the German's codes during WW II to
turn the tide of the war. In the summer of 1939, a small group of scholars became
codebreakers, working at Bletchley Part in England. This group of pioneering
codebreakers helped shorten the war and changed the course of history.
- **1946** - **ENIAC -** World's first electronic, large scale, general purpose computer, built by
Mauchly and Eckert, and activated at the University of Pennsylvania in 1946.
ENIAC recreated on a modern computer chip.The ENIAC is a 30 ton machine that measured 50 x 30 feet. It contained 19,000 vacuum tubes, 6000 switches, and could add 5,000 numbers in a second, a remarkable accomplishment at the time. A reprogrammable machine, the ENIAC performed initial calculations for the H-bomb. It was also used to prepare artillery shell trajectory tables and perform other military and scientific calculations. Since there was no software to reprogram the computer, people had to rewire it to get it to perform different functions. The human programmers had to read wiring diagrams and know what each switch did. J. Presper Eckert, Jr. and John W. Mauchly drew on Alansoff's work to create the ENIAC, the Electronic Numerical Integrator and Computer

# Computer Science

It’s the science of computers; it answers questions like

- What are the fundamental parts of a computer? What basic building blocks
 do you need?
- What can be computed, what cannot be?
- How easy or how fast can something be computed? What governs these
   metrics

# DataStructures & Algorithms

- How easy or how fast can something be computed? What governs these
metrics
- What are the basic building blocks or tools in our programming toolkit we need to write
 programs that are not inefficient
- What common pattern problems/patterns exist in programs and what are the known
 ways of speeding those up

## **Let’s say there is an alternate Universe**

Where two guys live in adjacent houses, Cory and Jamal. There’s no phones or computers yet in this universe, so Cory and Jamal do things like playing scrabble in their free time. Cory is the only one that owns a scrabble set, and since you can’t play alone the only way they can play is if Jamal goes to Cory’s place. But Cory’s parents are rather religious, and their religion’s scripture
says that there will one day be a game that youngster's play that will bring about the end of the world. Cory’s parents thus never want Cory to go near Scrabble.

It then becomes a game of cat and mouse between Cory and his parents, with him needing to hide his playing of scrabble. Cory’s father is a nurse who sometimes must do whole night shifts at
the hospital. Cory’s mother is a software engineer that sometimes works very late and is not home till 2am. These are they times Cory and Jamal get to play Scrabble. But they don’t have a fixed schedule, so they cannot be relied on to be absent every night. Cory has two table lamps at his desk which can be seen from Jamal’s window. So they come up with a scheme. If Cory’s mother isn’t home, Cory turns on the right lamp. If Cory’s father isn’t home he turns on the left lamp. Meaning that–if both lamps are on–it’s like an invite for Jamal to come play Scrabble if he feels like.

Now, sometimes Cory’s sister who’s usually at the University is at home, and on such days, they can only play till 1 am, which is when she comes out of her room to grab something to eat. And so Cory and Jamal decide that if his sister is home, he’ll turn on the ceiling fan in his room and Jamal will know that he can come only for a little while. For every extra piece of information Cory wanted to give to Jamal, they needed on more thing.  If it’s was only about his mom, just one lamp being on or off gives the requisite information – one thing. If you add his dad into the mix, you need two lamps-two things. If you add his sister to the mix, you need two lamps and a ceiling fan– three things.

### A processor in a computer kind of works in similar ways

- A processor in a computer has a set of operations it can do. Copy data, move data, Add data, subtract, multiply, divide, jump to another instruction, branch conditionally, etc.
- When you want to tell computer to do a certain operation, you need several things to convey this information about what to do to the Processor.
- Instead of lamps or fans being on or off, computers have very, very small wires with or without electricity.
- Presence or absence of Electricity conveys information about what to do. This, together, is known as one “Instruction
- Sometimes, just telling a processor to do something isn’t enough. Like for jumping,
you also need to tell the processor where to jump to, So you need additional wires to provide information on what Data to do the instruction on.
- Sometimes, like for say adding. One piece of information isn’t enough. You need to know two numbers to add them together.
- Sometimes, along with adding, you also need to tell the processor where to store
the result of whatever it is we are adding.
- Each of these 0 or 1 is known as a “bit”. 8 such bits together is known as a “byte”. The “size” of an instruction (the number of bits it has) depends on the kind of processor.  Most modern CPUs use 64 bits.

### Consider a Rube Goldberg machine

- It is a giant, very, very, complex contraption that has a bunch of lanes (each line below is a lane) which takes in the presence or absence of marbles, and the marbles rolling through the contraption causes some sort of side effect and this side effect is designed to be the intended operation.
- In the processor’s case, presence or absence of electricity rolls through the processor on a bunch of lanes and triggers some side effect and the processor is designed such that the side effect is our intended operation.
- It just so happens that the processor itself is very tiny and everything happens so fast that there is no good tools available to us that would let us see the operation of this rube Goldberg machine.

### Memory

- Memory is just a giant grid of cells which holds “electricity”.
- If we consider our previous example, think of it as a giant grid which as a bunch of balls stored in it and that you can open lanes from any cell to let the marble (electricity) roll on into the processor to do stuff with it.
- The processor has instructions which lets it select which cells to “open” roll marbles (data) from and use this data as instructions or operands, whichever.
- When I say Memory I mean RAM or Active memory.

### A program

- Is a region of your memory which holds instructions and data. When the first instruction from this region of memory starts going to the Processor we say that the program has started execution.

### Java Compiler

- Is a program that takes the “code” you write as text and turns it into a Program.
- That is, turns your code into a bunch of “bits” that are VALID
sequence of instructions for your processor to execute to do the thing
that your code wants to do.

### Program

- When we write and compile a program to “solve” an assignment, essentially we are creating sequences in memory filled with instructions that carry out, for example, the objective of assignment 1.
- Once the processor is done carrying out all these instructions, the assignment is complete.
- This is not exactly true, but the “GHz” or the gigahertz you see next to a processors specifications refers to the number of instructions the processor can execute in one second.
- If you have a 1GHz processor, you can execute 1 billion (10^12) instructions per second.

